---

resources:
- name: v-pod-repo
  type: git
  source:
    uri: git@github.com:manali14/gameOfLife.git
    branch: master

#- name: notify
#  type: slack-notification
#  source:
#    url: ((slack-webhook))
#
#resource_types:
#- name: slack-notification
#  type: docker-image
#  source:
#    repository: cfcommunity/slack-notification-resource
#    tag: latest

jobs:
- name: job-build-images
  public: true
  plan:
    - get: v-pod-repo
#      trigger: true
    - task: build-images
      file: task.yml
#      config:
#        platform: linux
#        run:
#          path: task.sh
      # on_failure:
      #      put: slack-alert
      #      params:
      #        channels: ci-pipeline
      #        text: |
      #          The $BUILD_PIPELINE_NAME build failed!
      #          https://channel.slack.com/archives/ci-pipeline/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      #        username: concourse_user
      #        icon_url: http://downloadicons.net/sites/default/files/error-icons-44565.png
      # on_success:
      #     put: slack-alert
      #     params:
      #       channels: ci-pipeline
      #       text: |
      #         The $BUILD_PIPELINE_NAME successfully deployed to dev space.
      #         https://channel.slack.com/archives/ci-pipeline/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
      #       username: concourse_user
      #       icon_url: http://vignette2.wikia.nocookie.net/legouniverse/images/f/f5/Jay_render.PNG/revision/latest?cb=20120406164257

